# Generated by Django 5.2.4 on 2025-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(default='default', max_length=100)),
                ('vector_index_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
