# Generated by Django 5.2.4 on 2025-07-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='vector_index_path',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uploadedpdf')),
            ],
        ),
    ]
