# Generated by Django 5.2.4 on 2025-07-12 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_uploadedpdf_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_history', to='core.uploadedpdf')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
