# Generated by Django 5.2.4 on 2025-07-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedpdf_uploaded_at_alter_uploadedpdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qahistory',
            name='session_id',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='qahistory',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uploadedpdf'),
        ),
    ]
